"""Fixed star catalog with J2000 ecliptic coordinates, magnitudes, and meanings."""

from typing import Dict, Any, List

FixedStarCatalog = Dict[str, Dict[str, Any]]

FIXED_STARS: FixedStarCatalog = {
    "aldebaran": {
        "name_en": "Aldebaran", "name_vi": "Aldebaran",
        "lon_j2000": 69.78, "lat": -5.47, "mag": 0.87, "orb": 2.5,
        "nature": "benefic", "constellation": "Taurus",
        "meaning_en": "Royal star of the East — honor, integrity, success through courage",
        "meaning_vi": "Sao Hoàng gia phương Đông — danh dự, chính trực, thành công qua can đảm",
        "keywords_en": ["leadership", "courage", "honor", "material success"],
        "keywords_vi": ["lãnh đạo", "can đảm", "danh dự", "thành công vật chất"],
    },
    "rigel": {
        "name_en": "Rigel", "name_vi": "Rigel",
        "lon_j2000": 78.93, "lat": -31.09, "mag": 0.13, "orb": 2.0,
        "nature": "benefic", "constellation": "Orion",
        "meaning_en": "Technical skill, inventiveness, success through intellect",
        "meaning_vi": "Kỹ năng kỹ thuật, sáng tạo, thành công qua trí tuệ",
        "keywords_en": ["invention", "skill", "intellect", "achievement"],
        "keywords_vi": ["phát minh", "kỹ năng", "trí tuệ", "thành tựu"],
    },
    "capella": {
        "name_en": "Capella", "name_vi": "Capella",
        "lon_j2000": 81.08, "lat": 22.52, "mag": 0.08, "orb": 2.0,
        "nature": "benefic", "constellation": "Auriga",
        "meaning_en": "Royal star — honor, authority, public recognition",
        "meaning_vi": "Sao Hoàng gia — danh dự, quyền uy, công nhận xã hội",
        "keywords_en": ["authority", "honor", "ambition", "fame"],
        "keywords_vi": ["quyền uy", "danh dự", "tham vọng", "danh tiếng"],
    },
    "betelgeuse": {
        "name_en": "Betelgeuse", "name_vi": "Betelgeuse",
        "lon_j2000": 88.87, "lat": -16.03, "mag": 0.42, "orb": 2.0,
        "nature": "ambivalent", "constellation": "Orion",
        "meaning_en": "Military honor, sudden fortune or downfall, impulsiveness",
        "meaning_vi": "Danh dự quân sự, thịnh vượng hoặc suy sụp đột ngột, bốc đồng",
        "keywords_en": ["sudden change", "impulse", "fortune", "risk"],
        "keywords_vi": ["thay đổi đột ngột", "bốc đồng", "may mắn", "rủi ro"],
    },
    "sirius": {
        "name_en": "Sirius", "name_vi": "Sirius",
        "lon_j2000": 101.82, "lat": -39.60, "mag": -1.46, "orb": 2.5,
        "nature": "benefic", "constellation": "Canis Major",
        "meaning_en": "Royal star — spiritual power, wealth, fame, protection",
        "meaning_vi": "Sao Hoàng gia — sức mạnh tâm linh, giàu có, danh vọng, bảo vệ",
        "keywords_en": ["spiritual power", "wealth", "fame", "protection"],
        "keywords_vi": ["sức mạnh tâm linh", "giàu có", "danh vọng", "bảo vệ"],
    },
    "procyon": {
        "name_en": "Procyon", "name_vi": "Procyon",
        "lon_j2000": 114.44, "lat": -15.99, "mag": 0.38, "orb": 2.0,
        "nature": "malefic", "constellation": "Canis Minor",
        "meaning_en": "Quick rise in life, impulsiveness, sudden changes",
        "meaning_vi": "Thăng tiến nhanh, bốc đồng, thay đổi đột ngột",
        "keywords_en": ["speed", "impulse", "sudden rise", "change"],
        "keywords_vi": ["tốc độ", "bốc đồng", "thăng tiến nhanh", "thay đổi"],
    },
    "pollux": {
        "name_en": "Pollux", "name_vi": "Pollux",
        "lon_j2000": 113.22, "lat": 6.68, "mag": 1.14, "orb": 2.0,
        "nature": "benefic", "constellation": "Gemini",
        "meaning_en": "Courage, martial spirit, protection in battle",
        "meaning_vi": "Can đảm, tinh thần chiến đấu, được bảo vệ trong xung đột",
        "keywords_en": ["courage", "protection", "combat", "victory"],
        "keywords_vi": ["can đảm", "bảo vệ", "chiến đấu", "chiến thắng"],
    },
    "castor": {
        "name_en": "Castor", "name_vi": "Castor",
        "lon_j2000": 110.14, "lat": 9.92, "mag": 1.58, "orb": 2.0,
        "nature": "ambivalent", "constellation": "Gemini",
        "meaning_en": "Intellectual ability, writing, sudden fame or violence",
        "meaning_vi": "Khả năng trí tuệ, viết lách, danh tiếng hoặc bạo lực bất ngờ",
        "keywords_en": ["intellect", "writing", "fame", "duality"],
        "keywords_vi": ["trí tuệ", "viết lách", "danh tiếng", "lưỡng tính"],
    },
    "regulus": {
        "name_en": "Regulus", "name_vi": "Regulus",
        "lon_j2000": 149.85, "lat": 0.46, "mag": 1.35, "orb": 2.5,
        "nature": "benefic", "constellation": "Leo",
        "meaning_en": "Royal star of the North — leadership, authority, noble ambition",
        "meaning_vi": "Sao Hoàng gia phương Bắc — lãnh đạo, quyền uy, tham vọng cao thượng",
        "keywords_en": ["leadership", "royalty", "authority", "ambition"],
        "keywords_vi": ["lãnh đạo", "vương quyền", "quyền uy", "tham vọng"],
    },
    "alphard": {
        "name_en": "Alphard", "name_vi": "Alphard",
        "lon_j2000": 141.07, "lat": -22.43, "mag": 2.01, "orb": 2.0,
        "nature": "malefic", "constellation": "Hydra",
        "meaning_en": "Wisdom through suffering, hidden knowledge, overcoming obstacles",
        "meaning_vi": "Trí tuệ qua đau khổ, tri thức ẩn giấu, vượt qua chướng ngại",
        "keywords_en": ["wisdom", "suffering", "hidden knowledge", "perseverance"],
        "keywords_vi": ["trí tuệ", "đau khổ", "tri thức ẩn", "kiên trì"],
    },
    "denebola": {
        "name_en": "Denebola", "name_vi": "Denebola",
        "lon_j2000": 173.47, "lat": 13.48, "mag": 2.14, "orb": 2.0,
        "nature": "ambivalent", "constellation": "Leo",
        "meaning_en": "Critical mind, judgment, regrets in later life",
        "meaning_vi": "Tư duy phê phán, phán xét, hối tiếc trong cuộc sống sau này",
        "keywords_en": ["judgment", "criticism", "analysis", "regret"],
        "keywords_vi": ["phán xét", "phê bình", "phân tích", "hối tiếc"],
    },
    "spica": {
        "name_en": "Spica", "name_vi": "Spica",
        "lon_j2000": 203.72, "lat": -2.05, "mag": 0.98, "orb": 2.5,
        "nature": "benefic", "constellation": "Virgo",
        "meaning_en": "Success, harmony, artistic talent, wealth, protection",
        "meaning_vi": "Thành công, hài hòa, tài năng nghệ thuật, giàu có, bảo vệ",
        "keywords_en": ["success", "harmony", "art", "wealth", "protection"],
        "keywords_vi": ["thành công", "hài hòa", "nghệ thuật", "giàu có", "bảo vệ"],
    },
    "arcturus": {
        "name_en": "Arcturus", "name_vi": "Arcturus",
        "lon_j2000": 204.47, "lat": 30.72, "mag": -0.05, "orb": 2.5,
        "nature": "benefic", "constellation": "Bootes",
        "meaning_en": "Prosperity, adventurous spirit, travel, exploration",
        "meaning_vi": "Thịnh vượng, tinh thần phiêu lưu, du lịch, khám phá",
        "keywords_en": ["prosperity", "adventure", "travel", "discovery"],
        "keywords_vi": ["thịnh vượng", "phiêu lưu", "du lịch", "khám phá"],
    },
    "zubenelgenubi": {
        "name_en": "Zubenelgenubi", "name_vi": "Zubenelgenubi",
        "lon_j2000": 222.53, "lat": 0.30, "mag": 2.75, "orb": 2.0,
        "nature": "ambivalent", "constellation": "Libra",
        "meaning_en": "Justice, balance, reform, social causes",
        "meaning_vi": "Công lý, cân bằng, cải cách, các vấn đề xã hội",
        "keywords_en": ["justice", "balance", "reform", "fairness"],
        "keywords_vi": ["công lý", "cân bằng", "cải cách", "công bằng"],
    },
    "antares": {
        "name_en": "Antares", "name_vi": "Antares",
        "lon_j2000": 249.85, "lat": -4.57, "mag": 0.96, "orb": 2.5,
        "nature": "malefic", "constellation": "Scorpius",
        "meaning_en": "Royal star of the West — passion, danger, military honor",
        "meaning_vi": "Sao Hoàng gia phương Tây — đam mê, nguy hiểm, danh dự quân sự",
        "keywords_en": ["passion", "danger", "warrior", "intensity"],
        "keywords_vi": ["đam mê", "nguy hiểm", "chiến binh", "mãnh liệt"],
    },
    "vega": {
        "name_en": "Vega", "name_vi": "Vega",
        "lon_j2000": 285.65, "lat": 61.85, "mag": 0.03, "orb": 2.5,
        "nature": "benefic", "constellation": "Lyra",
        "meaning_en": "Artistic talent, idealism, charm, popularity",
        "meaning_vi": "Tài năng nghệ thuật, lý tưởng, duyên dáng, nổi tiếng",
        "keywords_en": ["art", "idealism", "charm", "popularity"],
        "keywords_vi": ["nghệ thuật", "lý tưởng", "duyên dáng", "nổi tiếng"],
    },
    "altair": {
        "name_en": "Altair", "name_vi": "Altair",
        "lon_j2000": 301.77, "lat": 29.34, "mag": 0.77, "orb": 2.0,
        "nature": "benefic", "constellation": "Aquila",
        "meaning_en": "Boldness, ambition, determination, sudden success",
        "meaning_vi": "Táo bạo, tham vọng, quyết tâm, thành công bất ngờ",
        "keywords_en": ["boldness", "ambition", "determination", "success"],
        "keywords_vi": ["táo bạo", "tham vọng", "quyết tâm", "thành công"],
    },
    "deneb": {
        "name_en": "Deneb", "name_vi": "Deneb",
        "lon_j2000": 298.03, "lat": 59.95, "mag": 1.25, "orb": 2.0,
        "nature": "benefic", "constellation": "Cygnus",
        "meaning_en": "Intellectual brilliance, idealism, writing, vision",
        "meaning_vi": "Trí tuệ sáng chói, lý tưởng, viết lách, tầm nhìn",
        "keywords_en": ["brilliance", "idealism", "writing", "vision"],
        "keywords_vi": ["sáng chói", "lý tưởng", "viết lách", "tầm nhìn"],
    },
    "fomalhaut": {
        "name_en": "Fomalhaut", "name_vi": "Fomalhaut",
        "lon_j2000": 345.77, "lat": -21.08, "mag": 1.17, "orb": 2.5,
        "nature": "benefic", "constellation": "Piscis Austrinus",
        "meaning_en": "Royal star of the South — spiritual vision, fame, public recognition",
        "meaning_vi": "Sao Hoàng gia phương Nam — tầm nhìn tâm linh, danh tiếng, công nhận",
        "keywords_en": ["spirituality", "fame", "recognition", "vision"],
        "keywords_vi": ["tâm linh", "danh tiếng", "công nhận", "tầm nhìn"],
    },
    "markab": {
        "name_en": "Markab", "name_vi": "Markab",
        "lon_j2000": 353.78, "lat": 31.78, "mag": 2.48, "orb": 2.0,
        "nature": "malefic", "constellation": "Pegasus",
        "meaning_en": "Urgency, haste, danger from speed, need for caution",
        "meaning_vi": "Khẩn trương, vội vã, nguy hiểm từ tốc độ, cần thận trọng",
        "keywords_en": ["urgency", "speed", "caution", "impatience"],
        "keywords_vi": ["khẩn trương", "tốc độ", "thận trọng", "thiếu kiên nhẫn"],
    },
    "alpheratz": {
        "name_en": "Alpheratz", "name_vi": "Alpheratz",
        "lon_j2000": 14.02, "lat": 25.97, "mag": 2.07, "orb": 2.0,
        "nature": "benefic", "constellation": "Andromeda",
        "meaning_en": "Independence, leadership, success through personal effort",
        "meaning_vi": "Độc lập, lãnh đạo, thành công qua nỗ lực cá nhân",
        "keywords_en": ["independence", "leadership", "effort", "success"],
        "keywords_vi": ["độc lập", "lãnh đạo", "nỗ lực", "thành công"],
    },
    "hamal": {
        "name_en": "Hamal", "name_vi": "Hamal",
        "lon_j2000": 38.52, "lat": -9.98, "mag": 2.01, "orb": 2.0,
        "nature": "malefic", "constellation": "Aries",
        "meaning_en": "Impulse, aggression, leadership through force",
        "meaning_vi": "Bốc đồng, hung hăng, lãnh đạo qua sức mạnh",
        "keywords_en": ["impulse", "aggression", "force", "leadership"],
        "keywords_vi": ["bốc đồng", "hung hăng", "sức mạnh", "lãnh đạo"],
    },
    "algol": {
        "name_en": "Algol", "name_vi": "Algol",
        "lon_j2000": 49.99, "lat": 22.43, "mag": 2.09, "orb": 2.5,
        "nature": "malefic", "constellation": "Perseus",
        "meaning_en": "Most malefic fixed star — violence, danger, but also protection of the neck/head",
        "meaning_vi": "Sao xấu nhất — bạo lực, nguy hiểm, nhưng cũng bảo vệ vùng cổ/đầu",
        "keywords_en": ["danger", "violence", "intensity", "transformation"],
        "keywords_vi": ["nguy hiểm", "bạo lực", "mãnh liệt", "chuyển hóa"],
    },
    "pleiades": {
        "name_en": "Pleiades", "name_vi": "Pleiades",
        "lon_j2000": 59.87, "lat": 4.04, "mag": 1.6, "orb": 2.5,
        "nature": "ambivalent", "constellation": "Taurus",
        "meaning_en": "Weeping Sisters — ambition, vision, but also sorrow and loss",
        "meaning_vi": "Chị em khóc thương — tham vọng, tầm nhìn, nhưng cũng đau buồn và mất mát",
        "keywords_en": ["ambition", "vision", "sorrow", "intensity"],
        "keywords_vi": ["tham vọng", "tầm nhìn", "đau buồn", "mãnh liệt"],
    },
    "alghena": {
        "name_en": "Algena", "name_vi": "Algena",
        "lon_j2000": 103.91, "lat": 16.47, "mag": 1.93, "orb": 2.0,
        "nature": "benefic", "constellation": "Gemini",
        "meaning_en": "Strength, endurance, social success, generosity",
        "meaning_vi": "Sức mạnh, bền bỉ, thành công xã hội, hào phóng",
        "keywords_en": ["strength", "endurance", "success", "generosity"],
        "keywords_vi": ["sức mạnh", "bền bỉ", "thành công", "hào phóng"],
    },
    "acubens": {
        "name_en": "Acubens", "name_vi": "Acubens",
        "lon_j2000": 129.62, "lat": 11.70, "mag": 4.26, "orb": 1.5,
        "nature": "ambivalent", "constellation": "Cancer",
        "meaning_en": "Hidden talent, secret knowledge, psychic ability",
        "meaning_vi": "Tài năng ẩn giấu, tri thức bí mật, khả năng tâm linh",
        "keywords_en": ["psychic", "secrecy", "hidden talent", "intuition"],
        "keywords_vi": ["tâm linh", "bí mật", "tài năng ẩn", "trực giác"],
    },
    "zavijava": {
        "name_en": "Zavijava", "name_vi": "Zavijava",
        "lon_j2000": 175.80, "lat": 7.72, "mag": 3.61, "orb": 1.5,
        "nature": "benefic", "constellation": "Virgo",
        "meaning_en": "Charity, benevolence, intellectual pursuits",
        "meaning_vi": "Từ thiện, nhân ái, theo đuổi trí tuệ",
        "keywords_en": ["charity", "benevolence", "wisdom", "learning"],
        "keywords_vi": ["từ thiện", "nhân ái", "trí tuệ", "học hỏi"],
    },
    "vindemiatrix": {
        "name_en": "Vindemiatrix", "name_vi": "Vindemiatrix",
        "lon_j2000": 206.09, "lat": 14.79, "mag": 2.83, "orb": 2.0,
        "nature": "malefic", "constellation": "Virgo",
        "meaning_en": "Widowhood, loss, sacrifice, but also service to others",
        "meaning_vi": "Góa bụa, mất mát, hy sinh, nhưng cũng phục vụ người khác",
        "keywords_en": ["loss", "sacrifice", "service", "loneliness"],
        "keywords_vi": ["mất mát", "hy sinh", "phục vụ", "cô đơn"],
    },
    "zubeneschamali": {
        "name_en": "Zubeneschamali", "name_vi": "Zubeneschamali",
        "lon_j2000": 224.79, "lat": 8.41, "mag": 2.61, "orb": 2.0,
        "nature": "benefic", "constellation": "Libra",
        "meaning_en": "Restoration of justice, mercy, spiritual insight",
        "meaning_vi": "Khôi phục công lý, lòng thương xót, hiểu biết tâm linh",
        "keywords_en": ["justice", "mercy", "insight", "restoration"],
        "keywords_vi": ["công lý", "thương xót", "hiểu biết", "khôi phục"],
    },
    "ras_alhague": {
        "name_en": "Ras Alhague", "name_vi": "Ras Alhague",
        "lon_j2000": 262.02, "lat": 14.35, "mag": 2.08, "orb": 2.0,
        "nature": "benefic", "constellation": "Ophiuchus",
        "meaning_en": "Healing power, wisdom, protection from poison/disease",
        "meaning_vi": "Năng lực chữa lành, trí tuệ, bảo vệ khỏi độc tố/bệnh tật",
        "keywords_en": ["healing", "wisdom", "protection", "medicine"],
        "keywords_vi": ["chữa lành", "trí tuệ", "bảo vệ", "y học"],
    },
    "sabik": {
        "name_en": "Sabik", "name_vi": "Sabik",
        "lon_j2000": 252.08, "lat": 10.28, "mag": 2.43, "orb": 2.0,
        "nature": "ambivalent", "constellation": "Ophiuchus",
        "meaning_en": "Perseverance, patience, hope in difficult circumstances",
        "meaning_vi": "Kiên trì, nhẫn nại, hy vọng trong hoàn cảnh khó khăn",
        "keywords_en": ["perseverance", "patience", "hope", "endurance"],
        "keywords_vi": ["kiên trì", "nhẫn nại", "hy vọng", "chịu đựng"],
    },
    "kaus_australis": {
        "name_en": "Kaus Australis", "name_vi": "Kaus Australis",
        "lon_j2000": 283.99, "lat": 25.44, "mag": 1.85, "orb": 2.0,
        "nature": "benefic", "constellation": "Sagittarius",
        "meaning_en": "Adventurous spirit, exploration, higher education, travel",
        "meaning_vi": "Tinh thần phiêu lưu, khám phá, giáo dục cao, du lịch",
        "keywords_en": ["adventure", "exploration", "education", "travel"],
        "keywords_vi": ["phiêu lưu", "khám phá", "giáo dục", "du lịch"],
    },
    "nunki": {
        "name_en": "Nunki", "name_vi": "Nunki",
        "lon_j2000": 295.02, "lat": 25.41, "mag": 2.05, "orb": 2.0,
        "nature": "benefic", "constellation": "Sagittarius",
        "meaning_en": "Idealism, vision, philosophical insight, teaching",
        "meaning_vi": "Lý tưởng, tầm nhìn, hiểu biết triết học, giảng dạy",
        "keywords_en": ["idealism", "vision", "philosophy", "teaching"],
        "keywords_vi": ["lý tưởng", "tầm nhìn", "triết học", "giảng dạy"],
    },
    "enif": {
        "name_en": "Enif", "name_vi": "Enif",
        "lon_j2000": 331.99, "lat": 24.83, "mag": 2.39, "orb": 2.0,
        "nature": "malefic", "constellation": "Pegasus",
        "meaning_en": "Conflict, struggle, obstacles overcome through determination",
        "meaning_vi": "Xung đột, đấu tranh, vượt chướng ngại qua quyết tâm",
        "keywords_en": ["conflict", "struggle", "determination", "obstacles"],
        "keywords_vi": ["xung đột", "đấu tranh", "quyết tâm", "chướng ngại"],
    },
    "scheat": {
        "name_en": "Scheat", "name_vi": "Scheat",
        "lon_j2000": 341.99, "lat": 31.09, "mag": 2.42, "orb": 2.0,
        "nature": "malefic", "constellation": "Pegasus",
        "meaning_en": "Misfortune, accidents, but also survival and resilience",
        "meaning_vi": "Bất hạnh, tai nạn, nhưng cũng sống sót và kiên cường",
        "keywords_en": ["misfortune", "survival", "resilience", "caution"],
        "keywords_vi": ["bất hạnh", "sống sót", "kiên cường", "thận trọng"],
    },
    "diphda": {
        "name_en": "Diphda", "name_vi": "Diphda",
        "lon_j2000": 359.99, "lat": -42.89, "mag": 2.04, "orb": 2.0,
        "nature": "malefic", "constellation": "Cetus",
        "meaning_en": "Testing, trial, transformation through adversity",
        "meaning_vi": "Thử thách, gian nan, chuyển hóa qua nghịch cảnh",
        "keywords_en": ["testing", "adversity", "transformation", "strength"],
        "keywords_vi": ["thử thách", "nghịch cảnh", "chuyển hóa", "sức mạnh"],
    },
    "acamar": {
        "name_en": "Acamar", "name_vi": "Acamar",
        "lon_j2000": 322.53, "lat": -44.63, "mag": 3.01, "orb": 1.5,
        "nature": "benefic", "constellation": "Eridanus",
        "meaning_en": "Completion, fulfillment, spiritual achievement",
        "meaning_vi": "Hoàn thành, viên mãn, thành tựu tâm linh",
        "keywords_en": ["completion", "fulfillment", "spiritual", "achievement"],
        "keywords_vi": ["hoàn thành", "viên mãn", "tâm linh", "thành tựu"],
    },
    "polaris": {
        "name_en": "Polaris", "name_vi": "Polaris",
        "lon_j2000": 135.00, "lat": 66.57, "mag": 1.97, "orb": 2.0,
        "nature": "benefic", "constellation": "Ursa Minor",
        "meaning_en": "Guidance, direction, spiritual purpose, destiny",
        "meaning_vi": "Hướng dẫn, định hướng, mục đích tâm linh, định mệnh",
        "keywords_en": ["guidance", "direction", "destiny", "purpose"],
        "keywords_vi": ["hướng dẫn", "định hướng", "định mệnh", "mục đích"],
    },
    "dubhe": {
        "name_en": "Dubhe", "name_vi": "Dubhe",
        "lon_j2000": 163.48, "lat": 49.30, "mag": 1.79, "orb": 2.0,
        "nature": "benefic", "constellation": "Ursa Major",
        "meaning_en": "Strength, stability, wisdom, grounded power",
        "meaning_vi": "Sức mạnh, ổn định, trí tuệ, quyền lực vững chắc",
        "keywords_en": ["strength", "stability", "wisdom", "power"],
        "keywords_vi": ["sức mạnh", "ổn định", "trí tuệ", "quyền lực"],
    },
    "alkaid": {
        "name_en": "Alkaid", "name_vi": "Alkaid",
        "lon_j2000": 184.50, "lat": 48.96, "mag": 1.86, "orb": 2.0,
        "nature": "ambivalent", "constellation": "Ursa Major",
        "meaning_en": "Martial spirit, death or transformation, spiritual calling",
        "meaning_vi": "Tinh thần chiến binh, chết hoặc chuyển hóa, tiếng gọi tâm linh",
        "keywords_en": ["warrior", "transformation", "spiritual", "calling"],
        "keywords_vi": ["chiến binh", "chuyển hóa", "tâm linh", "tiếng gọi"],
    },
    "cor_caroli": {
        "name_en": "Cor Caroli", "name_vi": "Cor Caroli",
        "lon_j2000": 193.00, "lat": 40.37, "mag": 2.89, "orb": 1.5,
        "nature": "benefic", "constellation": "Canes Venatici",
        "meaning_en": "Loyalty, devotion, protection of loved ones",
        "meaning_vi": "Trung thành, tận tụy, bảo vệ người thân yêu",
        "keywords_en": ["loyalty", "devotion", "protection", "love"],
        "keywords_vi": ["trung thành", "tận tụy", "bảo vệ", "tình yêu"],
    },
    "porrima": {
        "name_en": "Porrima", "name_vi": "Porrima",
        "lon_j2000": 193.00, "lat": 15.69, "mag": 3.44, "orb": 1.5,
        "nature": "benefic", "constellation": "Virgo",
        "meaning_en": "Prophecy, divination, goddess of prophecy, hidden knowledge",
        "meaning_vi": "Tiên tri, bói toán, nữ thần tiên tri, tri thức ẩn",
        "keywords_en": ["prophecy", "divination", "wisdom", "mystery"],
        "keywords_vi": ["tiên tri", "bói toán", "trí tuệ", "huyền bí"],
    },
    "menkent": {
        "name_en": "Menkent", "name_vi": "Menkent",
        "lon_j2000": 209.99, "lat": 22.83, "mag": 2.06, "orb": 2.0,
        "nature": "benefic", "constellation": "Centaurus",
        "meaning_en": "Generosity, magnanimity, moral leadership",
        "meaning_vi": "Hào phóng, độ lượng, lãnh đạo đạo đức",
        "keywords_en": ["generosity", "leadership", "morality", "nobility"],
        "keywords_vi": ["hào phóng", "lãnh đạo", "đạo đức", "cao thượng"],
    },
    "unuk": {
        "name_en": "Unuk", "name_vi": "Unuk",
        "lon_j2000": 229.99, "lat": 36.69, "mag": 2.63, "orb": 2.0,
        "nature": "malefic", "constellation": "Serpens",
        "meaning_en": "Caution, hidden enemies, intrigue, need for discernment",
        "meaning_vi": "Thận trọng, kẻ thù ẩn, mưu đồ, cần phán đoán sáng suốt",
        "keywords_en": ["caution", "intrigue", "discernment", "secrecy"],
        "keywords_vi": ["thận trọng", "mưu đồ", "phán đoán", "bí mật"],
    },
    "shaula": {
        "name_en": "Shaula", "name_vi": "Shaula",
        "lon_j2000": 259.99, "lat": -3.20, "mag": 1.62, "orb": 2.0,
        "nature": "malefic", "constellation": "Scorpius",
        "meaning_en": "Danger, treachery, but also sharp intelligence",
        "meaning_vi": "Nguy hiểm, phản bội, nhưng cũng trí thông minh sắc sảo",
        "keywords_en": ["danger", "treachery", "intelligence", "sharpness"],
        "keywords_vi": ["nguy hiểm", "phản bội", "thông minh", "sắc sảo"],
    },
    "lesath": {
        "name_en": "Lesath", "name_vi": "Lesath",
        "lon_j2000": 262.99, "lat": -8.39, "mag": 2.70, "orb": 2.0,
        "nature": "malefic", "constellation": "Scorpius",
        "meaning_en": "Poison, stinging criticism, but also penetrating insight",
        "meaning_vi": "Độc tố, chỉ trích cay độc, nhưng cũng thấu hiểu sâu sắc",
        "keywords_en": ["criticism", "poison", "insight", "penetration"],
        "keywords_vi": ["chỉ trích", "độc hại", "thấu hiểu", "xuyên thấu"],
    },
    "sadalsuud": {
        "name_en": "Sadalsuud", "name_vi": "Sadalsuud",
        "lon_j2000": 327.99, "lat": 20.67, "mag": 2.90, "orb": 2.0,
        "nature": "benefic", "constellation": "Aquarius",
        "meaning_en": "Luck, fortune, happiness, prosperous journeys",
        "meaning_vi": "May mắn, tài lộc, hạnh phúc, hành trình thịnh vượng",
        "keywords_en": ["luck", "fortune", "happiness", "prosperity"],
        "keywords_vi": ["may mắn", "tài lộc", "hạnh phúc", "thịnh vượng"],
    },
    "sadalmelik": {
        "name_en": "Sadalmelik", "name_vi": "Sadalmelik",
        "lon_j2000": 331.99, "lat": 10.87, "mag": 2.95, "orb": 2.0,
        "nature": "benefic", "constellation": "Aquarius",
        "meaning_en": "Authority, power, service to humanity, public office",
        "meaning_vi": "Quyền uy, sức mạnh, phục vụ nhân loại, chức vụ công",
        "keywords_en": ["authority", "power", "service", "public role"],
        "keywords_vi": ["quyền uy", "sức mạnh", "phục vụ", "vai trò công"],
    },
    "skat": {
        "name_en": "Skat", "name_vi": "Skat",
        "lon_j2000": 339.99, "lat": 5.08, "mag": 3.27, "orb": 1.5,
        "nature": "benefic", "constellation": "Aquarius",
        "meaning_en": "Wishes, dreams, spiritual fulfillment, hope",
        "meaning_vi": "Ước vọng, giấc mơ, viên mãn tâm linh, hy vọng",
        "keywords_en": ["wishes", "dreams", "fulfillment", "hope"],
        "keywords_vi": ["ước vọng", "giấc mơ", "viên mãn", "hy vọng"],
    },
    "algedi": {
        "name_en": "Algedi", "name_vi": "Algedi",
        "lon_j2000": 309.99, "lat": -5.85, "mag": 3.57, "orb": 2.0,
        "nature": "ambivalent", "constellation": "Capricorn",
        "meaning_en": "Sacrifice, duty, patience rewarded, long-term success",
        "meaning_vi": "Hy sinh, bổn phận, kiên nhẫn được đền đáp, thành công lâu dài",
        "keywords_en": ["sacrifice", "duty", "patience", "long-term success"],
        "keywords_vi": ["hy sinh", "bổn phận", "kiên nhẫn", "thành công lâu dài"],
    },
    "dabih": {
        "name_en": "Dabih", "name_vi": "Dabih",
        "lon_j2000": 313.99, "lat": -7.69, "mag": 3.05, "orb": 2.0,
        "nature": "ambivalent", "constellation": "Capricorn",
        "meaning_en": "Fortune through business, commerce, but also greed",
        "meaning_vi": "May mắn qua kinh doanh, thương mại, nhưng cũng tham lam",
        "keywords_en": ["business", "commerce", "wealth", "greed"],
        "keywords_vi": ["kinh doanh", "thương mại", "giàu có", "tham lam"],
    },
    "acrab": {
        "name_en": "Acrab", "name_vi": "Acrab",
        "lon_j2000": 246.99, "lat": -17.04, "mag": 2.82, "orb": 2.0,
        "nature": "malefic", "constellation": "Scorpius",
        "meaning_en": "Hidden dangers, poison, but also scientific ability",
        "meaning_vi": "Nguy hiểm ẩn, độc tố, nhưng cũng khả năng khoa học",
        "keywords_en": ["danger", "science", "research", "secrecy"],
        "keywords_vi": ["nguy hiểm", "khoa học", "nghiên cứu", "bí mật"],
    },
    "rukbat": {
        "name_en": "Rukbat", "name_vi": "Rukbat",
        "lon_j2000": 271.99, "lat": -13.52, "mag": 3.97, "orb": 1.5,
        "nature": "benefic", "constellation": "Sagittarius",
        "meaning_en": "Archery, focus, aiming at goals, precision",
        "meaning_vi": "Bắn cung, tập trung, nhắm mục tiêu, chính xác",
        "keywords_en": ["focus", "precision", "goals", "determination"],
        "keywords_vi": ["tập trung", "chính xác", "mục tiêu", "quyết tâm"],
    },
}

FIXED_STAR_LIST: List[str] = list(FIXED_STARS.keys())
