"""House Synthesis data — multi-variable engine support.

Layers (per user architecture):
  BASE      = cusp sign flavor (12 houses x 12 signs)  -- the foundation
  OCCUPANT  = planet(s) actually IN the house          -- primary modifier (highest weight)
  RULER     = ruler of the cusp sign, and which house it sits in -- the drive/link
  ASPECT    = harmony/dissonance among occupants & ruler -- the variation

Normalization rules (mandated):
  - VI and EN are fully SEPARATE blocks; no English words inside VI text.
  - No age/content labels (e.g. "18+"); describe the astrological flavor only.
  - Same sentence structure across all 12 signs for consistency.
"""
from typing import Dict

# ── BASE layer: cusp-sign flavor per house (HOUSE -> SIGN -> text) ──────────
# One sentence: the "attitude / flavour" the house takes when this sign is on its cusp.
HOUSE_BASE_VI: Dict[int, Dict[str, str]] = {
    1: {  # Bản thân / cá tính
        "aries": "Bạn bước vào đời với sự chủ động, bộc trực; cá tính mạnh, thích tiên phong.",
        "taurus": "Bạn thể hiện bản thân chậm rãi, vững chãi; giữ gìn hình ảnh và giá trị cá nhân.",
        "gemini": "Bản thân bạn linh hoạt, đa dạng; bạn thích thay đổi vai trò và giao tiếp.",
        "cancer": "Bạn có mặt ngoài nhạy cảm, bảo vệ; căn tính gắn với an toàn và nguồn cội.",
        "leo": "Bạn phát lộ cá tính nồng nhiệt, tự tin; muốn được nhìn nhận và tỏa sáng.",
        "virgo": "Bạn thể hiện mình qua sự tỉ mỉ, chu đáo; cầu toàn trong cách xuất hiện.",
        "libra": "Bản thân bạn hài hòa, lịch thiệp; bạn tìm sự cân bằng trong cách đối nhân xử thế.",
        "scorpio": "Bạn có mặt ngoài sâu, kín đáo; căn tính mang tính tập trung và quyết liệt.",
        "sagittarius": "Bạn bước ra thế giới với sự cởi mở, ham hiểu biết; thích tự do và mở rộng.",
        "capricorn": "Bản thân bạn nghiêm túc, kỷ luật; bạn xây dựng hình ảnh qua nỗ lực bền bỉ.",
        "aquarius": "Bạn thể hiện cá tính độc lập, khác biệt; coi trọng tư duy và cộng đồng.",
        "pisces": "Bạn có mặt ngoài mềm mại, thấu cảm; căn tính hòa tan vào cảm xúc chung.",
    },
    2: {  # Tài chính / giá trị
        "aries": "Tiền và giá trị với bạn là năng lượng dám làm, nhanh; dễ kiếm nhanh cũng dễ tiêu nhanh.",
        "taurus": "Bạn coi trọng sự sở hữu bền vững; tích lũy từ từ và gắn bó với vật chất.",
        "gemini": "Tài chính của bạn linh hoạt, đa nguồn; bạn thích học hỏi và trao đổi giá trị.",
        "cancer": "Giá trị của bạn gắn với an toàn và chăm sóc; giữ gìn của cải như giữ gìn gia đình.",
        "leo": "Bạn kiếm tiền để được trọng vọng; tiêu dùng mang tính trình diễn và hào phóng.",
        "virgo": "Bạn quản lý tài chính tỉ mỉ, thực tế; giá trị nằm ở sự hữu dụng.",
        "libra": "Bạn tìm sự cân bằng trong chi tiêu; giá trị gắn với thẩm mỹ và quan hệ.",
        "scorpio": "Tiền với bạn là quyền lực và sự sâu sắc; bạn quản lý kín đáo, tập trung.",
        "sagittarius": "Tài chính của bạn gắn với cơ hội mở rộng; thích đầu tư vào trải nghiệm và tri thức.",
        "capricorn": "Bạn xây dựng tài sản qua kỷ luật dài hạn; trọng sự ổn định và uy tín.",
        "aquarius": "Bạn coi tiền như công cụ cho ý tưởng; chi tiêu khác biệt, hướng cộng đồng.",
        "pisces": "Giá trị của bạn mang tính cảm xúc và chia sẻ; dễ xót xa nhưng cũng dễ buông.",
    },
    3: {  # Giao tiếp / anh chị em
        "aries": "Bạn nói nhanh, trực tiếp, hay chủ động dẫn dắt cuộc trò chuyện.",
        "taurus": "Giao tiếp của bạn chậm rãi, thực tế; thích nói những điều chắc chắn.",
        "gemini": "Bạn là người nói chuyện lưu loát, đa đề tài; tư duy nhanh và tò mò.",
        "cancer": "Bạn giao tiếp nhẹ nhàng, bảo vệ; lời nói gắn với cảm xúc và gia đình.",
        "leo": "Bạn phát biểu tự tin, kể chuyện cuốn hút; thích được chú ý khi nói.",
        "virgo": "Bạn nói rành mạch, chi tiết; trọng sự chính xác và hữu ích.",
        "libra": "Bạn ăn nói hòa nhã, cân nhắc; thích thảo luận và làm trung gian.",
        "scorpio": "Bạn nói ít nhưng sâu; lời có sức nặng và hay đào xoáy bản chất.",
        "sagittarius": "Bạn nói thẳng, rộng mở; thích chia sẻ quan điểm và triết lý.",
        "capricorn": "Giao tiếp của bạn nghiêm túc, có mục đích; trọng uy tín lời nói.",
        "aquarius": "Bạn nói độc lập, khác biệt; thích ý tưởng mới lạ và khách quan.",
        "pisces": "Bạn giao tiếp mềm mại, hình ảnh; hay dùng ẩn dụ và đồng cảm.",
    },
    4: {  # Gia đình / nguồn cội
        "aries": "Gia đình với bạn là nơi bạn chủ động, đôi khi nóng nảy; thích tự quyết trong nhà.",
        "taurus": "Bạn tạo tổ ấm vững chãi, truyền thống; trọng sự ổn định vật chất.",
        "gemini": "Không khí gia đình linh hoạt, nhiều hoạt động; bạn thích giao lưu ngay tại nhà.",
        "cancer": "Gia đình là cội rễ sâu của bạn; bạn bảo vệ người thân bằng cảm xúc mãnh liệt.",
        "leo": "Bạn là trung tâm ấm cúng của gia đình; thích chăm lo và được quý mến.",
        "virgo": "Bạn chăm sóc nhà cửa tỉ mỉ, ngăn nắp; trọng sự tiện nghi thực tế.",
        "libra": "Không gian gia đình hài hòa, thẩm mỹ; bạn ghét xung đột trong nhà.",
        "scorpio": "Gia đình với bạn mang tính riêng tư, sâu; gắn bó nhưng kén chia sẻ.",
        "sagittarius": "Bạn thích nhà cửa cởi mở, tự do; gia đình gắn với việc mở rộng tầm nhìn.",
        "capricorn": "Bạn xây dựng gia đình qua kỷ luật và trách nhiệm; trọng truyền thống.",
        "aquarius": "Không khí gia đình khác biệt, cởi mở; bạn coi trọng tự do của mỗi người.",
        "pisces": "Gia đình với bạn mềm mại, đồng cảm; dễ hòa tan vào cảm xúc chung.",
    },
    5: {  # Sáng tạo / tình cảm / con cái
        "aries": "Bạn sáng tạo bùng nổ, thích dẫn dắt; tình cảm nhiệt tình và trực tiếp.",
        "taurus": "Bạn yêu và sáng tạo bằng sự gắn kết bền; thích cái đẹp và xúc giác.",
        "gemini": "Bạn chơi đa dạng, tò mò; tình cảm nhẹ nhàng, thích giao lưu và học hỏi.",
        "cancer": "Bạn yêu sâu, bảo vệ; sáng tạo gắn với cảm xúc và nuôi dưỡng.",
        "leo": "Bạn sáng tạo nồng nhiệt, thích được ngợi khen; tình cảm rực rỡ, chung thủy.",
        "virgo": "Bạn sáng tạo tỉ mỉ, thực tế; yêu qua sự phục vụ và để ý chi tiết.",
        "libra": "Bạn sáng tạo hài hòa, lãng mạn; tình cảm nhẹ nhàng, cần sự cân bằng.",
        "scorpio": "Bạn sáng tạo và yêu với cường độ sâu; tình cảm chiếm hữu và biến đổi.",
        "sagittarius": "Bạn sáng tạo tự do, phiêu lưu; tình cảm cởi mở, thích mở rộng cùng người kia.",
        "capricorn": "Bạn sáng tạo kỷ luật, bền bỉ; tình cảm chín chắn, có trách nhiệm.",
        "aquarius": "Bạn sáng tạo khác biệt, độc lập; tình cảm bạn bè, không ràng buộc.",
        "pisces": "Bạn sáng tạo mơ mộng, đồng cảm; tình cảm tan biến, thấu cảm sâu.",
    },
    6: {  # Công việc / sức khỏe
        "aries": "Bạn làm việc nhanh, chủ động; thích hành động hơn quy trình.",
        "taurus": "Bạn làm việc đều đặn, kiên trì; trọng sự ổn định và hiệu quả thực tế.",
        "gemini": "Bạn đa việc, linh hoạt; thích công việc có giao tiếp và thay đổi.",
        "cancer": "Bạn làm việc bảo vệ, chăm sóc; sức khỏe gắn với cảm xúc.",
        "leo": "Bạn làm việc tự tin, thích dẫn dắt; muốn được ghi nhận.",
        "virgo": "Bạn làm việc tỉ mỉ, chuẩn xác; sức khỏe cần kỷ luật hàng ngày.",
        "libra": "Bạn làm việc hài hòa, hợp tác; thích môi trường cân bằng.",
        "scorpio": "Bạn làm việc tập trung, sâu; sức khỏe nhạy với căng thẳng nội tâm.",
        "sagittarius": "Bạn làm việc cởi mở, thích ý nghĩa; ghét khuôn mẫu gò bó.",
        "capricorn": "Bạn làm việc kỷ luật, trách nhiệm; sức khỏe xây qua thói quen bền.",
        "aquarius": "Bạn làm việc độc lập, khác biệt; thích đổi mới và tự chủ.",
        "pisces": "Bạn làm việc đồng cảm, linh hoạt; sức khỏe nhạy với trạng thái tâm trí.",
    },
    7: {  # Hôn nhân / đối tác
        "aries": "Bạn chọn bạn đời chủ động, bộc trực; quan hệ cần sự nhiệt tình.",
        "taurus": "Bạn cần bạn đời bền vững, tin cậy; quan hệ gắn kết sâu về vật chất.",
        "gemini": "Bạn thích đối tác thông minh, đa dạng; quan hệ cần giao tiếp và mới mẻ.",
        "cancer": "Bạn cần bạn đời che chở, thấu cảm; quan hệ gắn với an toàn.",
        "leo": "Bạn thích đối tác ngưỡng mộ mình; quan hệ nồng nhiệt, chung thủy.",
        "virgo": "Bạn cần bạn đời chu đáo, thực tế; quan hệ qua phục vụ lẫn nhau.",
        "libra": "Bạn tìm bạn đời hài hòa, thẩm mỹ; quan hệ cần sự cân bằng.",
        "scorpio": "Bạn cần bạn đời sâu sắc, tuyệt đối; quan hệ chiếm hữu và biến đổi.",
        "sagittarius": "Bạn thích đối tác cởi mở, cùng khám phá; quan hệ cần tự do.",
        "capricorn": "Bạn cần bạn đời trách nhiệm, vững chãi; quan hệ bền vững lâu dài.",
        "aquarius": "Bạn thích đối tác độc lập, bạn bè; quan hệ không ràng buộc gò bó.",
        "pisces": "Bạn cần bạn đời thấu cảm, mềm mại; quan hệ hòa tan và đồng cảm.",
    },
    8: {  # Thân mật / tài sản chung / biến đổi
        "aries": "Bạn tiếp cận sự thân mật trực tiếp, bùng nổ; thích chủ động và nhiệt huyết, dễ cháy lẹ tắt lẹ.",
        "taurus": "Bạn gắn kết sâu về xác thịt và vật chất; chậm mà bền, trung thành nhưng hay gắn chặt.",
        "gemini": "Bạn đa dạng trong cách thể hiện sự gần gũi; thích khám phá và đổi mới trải nghiệm gắn kết.",
        "cancer": "Bạn thân mật qua sự chăm sóc và tổn thương; cần an toàn mới mở lòng, một khi tin thì sâu.",
        "leo": "Bạn gắn kết nồng nhiệt, thích được ngưỡng mộ; coi sự thân mật là cách tỏa sáng cùng người kia.",
        "virgo": "Bạn e dè, để ý từng chi tiết của đối phương; thể hiện qua phục vụ, cần tin cậy mới buông.",
        "libra": "Bạn thân mật hài hòa, thẩm mỹ; cần sự cân bằng và đẹp đẽ trong gắn kết.",
        "scorpio": "Bạn gắn kết cực độ sâu, chiếm hữu và biến đổi; đòi hỏi tin cậy tuyệt đối, trung thành đến cùng.",
        "sagittarius": "Bạn cởi mở, phiêu lưu trong gắn kết; thích mở rộng cùng người kia, ghét sự bó buộc.",
        "capricorn": "Bạn kín đáo, kiềm chế; xây dựng gắn kết lâu dài qua cam kết và thời gian.",
        "aquarius": "Bạn thân mật khác biệt, độc lập; coi gắn kết là sự kết nối tự do, không chiếm hữu.",
        "pisces": "Bạn hòa tan trong gắn kết, đồng cảm sâu; cần người đủ vững để neo giữ bạn.",
    },
    9: {  # Triết lý / du lịch / học cao
        "aries": "Bạn học và khám phá chủ động, thích tiên phong quan điểm riêng.",
        "taurus": "Bạn tiếp thu chậm nhưng vững; trọng tri thức thực tế và truyền thống.",
        "gemini": "Bạn ham học đa đề tài, giao lưu ý tưởng; thích trao đổi hơn nghiên cứu sâu.",
        "cancer": "Bạn học qua cảm xúc và ký ức; triết lý gắn với nguồn cội.",
        "leo": "Bạn thích chia sẻ quan điểm tự tin; học để tỏa sáng và dẫn dắt.",
        "virgo": "Bạn học tỉ mỉ, phân tích; trọng tri thức hữu dụng.",
        "libra": "Bạn tìm sự cân bằng trong quan điểm; thích thảo luận triết lý.",
        "scorpio": "Bạn đào sâu bản chất; triết lý mang tính biến đổi và tâm lý.",
        "sagittarius": "Bạn khao khát mở rộng chân trời; học và du lịch là cách sống.",
        "capricorn": "Bạn học kỷ luật, có hệ thống; trọng tri thức mang tính xây dựng.",
        "aquarius": "Bạn học độc lập, khác biệt; thích ý tưởng tiến bộ và khách quan.",
        "pisces": "Bạn học qua trực giác và đồng cảm; triết lý mang tính thấu cảm.",
    },
    10: {  # Sự nghiệp / danh tiếng
        "aries": "Bạn thăng tiến chủ động, dám dẫn dắt; thích làm việc quyết đoán.",
        "taurus": "Bạn xây dựng sự nghiệp bền vững; trọng vị thế vật chất và ổn định.",
        "gemini": "Bạn đa vai trò, thích giao tiếp trong nghề; linh hoạt đổi hướng.",
        "cancer": "Bạn gắn sự nghiệp với mong muốn bảo vệ; cần môi trường an toàn.",
        "leo": "Bạn tỏa sáng trong nghề, thích dẫn dắt; cần được ghi nhận.",
        "virgo": "Bạn làm nghề tỉ mỉ, chuẩn xác; trọng hiệu quả và phục vụ.",
        "libra": "Bạn thành công qua hợp tác và thẩm mỹ; thích môi trường hài hòa.",
        "scorpio": "Bạn quyết liệt, sâu trong nghề; thích quyền lực và tầm ảnh hưởng.",
        "sagittarius": "Bạn thích nghề có ý nghĩa, mở rộng; ghét gò bó hành chính.",
        "capricorn": "Bạn xây dựng sự nghiệp qua kỷ luật; trọng uy tín và thăng tiến bền.",
        "aquarius": "Bạn làm nghề độc lập, đổi mới; thích tác động đến cộng đồng.",
        "pisces": "Bạn làm nghề đồng cảm, sáng tạo; thích ý nghĩa hơn danh lợi.",
    },
    11: {  # Bạn bè / lý tưởng
        "aries": "Bạn kết bạn chủ động, thích dẫn dắt nhóm; bạn bè năng động.",
        "taurus": "Bạn có bạn thân lâu bền; trọng sự gắn kết thực tế.",
        "gemini": "Bạn kết nối rộng, đa nhóm; thích giao lưu và trao đổi ý tưởng.",
        "cancer": "Bạn coi bạn bè như gia đình; quan hệ gắn với sự chăm sóc.",
        "leo": "Bạn thích làm trung tâm nhóm; bạn bè nồng nhiệt, chung thủy.",
        "virgo": "Bạn kết bạn qua sự giúp đỡ; trọng bạn thực tế, tỉ mỉ.",
        "libra": "Bạn kết bạn hài hòa, cân bằng; thích nhóm hòa hợp.",
        "scorpio": "Bạn có bạn thân ít nhưng sâu; quan hệ gắn kết và tin cậy tuyệt đối.",
        "sagittarius": "Bạn thích bạn cởi mở, cùng khám phá; nhóm mang tính mở rộng.",
        "capricorn": "Bạn kết bạn có chọn lọc, vững chãi; trọng uy tín trong nhóm.",
        "aquarius": "Bạn kết nối rộng khắp, khác biệt; bạn bè gắn với lý tưởng chung.",
        "pisces": "Bạn đồng cảm với bạn bè; quan hệ mềm mại, thấu cảm.",
    },
    12: {  # Tiềm thức / tâm linh
        "aries": "Bạn có nội lực chủ động, đôi khi hành động theo thôi thúc vô thức.",
        "taurus": "Bạn tĩnh lặng, cần an toàn trong thế giới tâm linh; chậm mà sâu.",
        "gemini": "Bạn tư duy tiềm thức linh hoạt, đa chiều; hay mơ và kết nối ý tưởng.",
        "cancer": "Bạn nhạy cảm sâu ở tầng vô thức; cảm xúc cũ dễ trỗi dậy.",
        "leo": "Bạn có cái tôi vô thức mạnh; cần được khẳng định cả trong thầm kín.",
        "virgo": "Bạn phân tích nội tâm tỉ mỉ; dễ lo âu qua chi tiết.",
        "libra": "Bạn tìm sự cân bằng trong tâm linh; dễ dao động giữa các cực.",
        "scorpio": "Bạn có tầng vô thức sâu và mạnh; dễ gặm nhấm cảm xúc thầm kín.",
        "sagittarius": "Bạn tìm ý nghĩa tâm linh rộng mở; thích tín ngưỡng tự do.",
        "capricorn": "Bạn kỷ luật cả nội tâm; cần thời gian mới mở lòng với vô thức.",
        "aquarius": "Bạn tiếp cận tâm linh khách quan, khác biệt; thích cái nhìn vượt thời đại.",
        "pisces": "Bạn hòa tan hoàn toàn vào tầng vô thức; trực giác và mơ mộng mãnh liệt.",
    },
}

HOUSE_BASE_EN: Dict[int, Dict[str, str]] = {
    1: {
        "aries": "You meet the world directly and initiatively; a strong, pioneering self.",
        "taurus": "You present yourself steady and deliberate; you guard your image and values.",
        "gemini": "Your self is flexible and varied; you enjoy shifting roles and communicating.",
        "cancer": "Your outer self is sensitive and protective; identity ties to safety and roots.",
        "leo": "You show a warm, confident self; you want to be seen and to shine.",
        "virgo": "You express yourself through precision and care; perfectionist in presentation.",
        "libra": "Your self is harmonious and polite; you seek balance in relating.",
        "scorpio": "Your outer self is deep and private; identity is focused and intense.",
        "sagittarius": "You face the world open and curious; you prize freedom and expansion.",
        "capricorn": "Your self is serious and disciplined; built through steady effort.",
        "aquarius": "You show an independent, different self; you value thought and community.",
        "pisces": "Your outer self is soft and empathic; identity dissolves into shared feeling.",
    },
    2: {
        "aries": "Money and values are active energy for you; quick to earn, quick to spend.",
        "taurus": "You value durable ownership; you accumulate slowly and bond with matter.",
        "gemini": "Your finances are flexible and varied; you like learning and exchanging value.",
        "cancer": "Your values tie to safety and care; you keep wealth like you keep family.",
        "leo": "You earn to be esteemed; spending is expressive and generous.",
        "virgo": "You manage money precisely and practically; value lies in usefulness.",
        "libra": "You balance spending; value ties to beauty and relationship.",
        "scorpio": "Money is power and depth for you; managed privately and focused.",
        "sagittarius": "Finance links to expanding opportunity; you invest in experience and meaning.",
        "capricorn": "You build assets through long-term discipline; stability and standing matter.",
        "aquarius": "You treat money as a tool for ideas; spending is unconventional, communal.",
        "pisces": "Your values are emotional and giving; easily moved, easily released.",
    },
    3: {
        "aries": "You speak fast and directly, often leading the conversation.",
        "taurus": "Your communication is slow and practical; you say what you mean.",
        "gemini": "You are fluent and wide-ranging; quick, curious thinking.",
        "cancer": "You communicate gently and protectively; words carry feeling and family.",
        "leo": "You speak with confidence and story; you like attention when talking.",
        "virgo": "You speak clearly and in detail; you prize accuracy and usefulness.",
        "libra": "You speak gracefully and even-handedly; you like discussion and mediation.",
        "scorpio": "You say little but deep; words carry weight and dig to essence.",
        "sagittarius": "You speak plainly and openly; you share viewpoints and philosophy.",
        "capricorn": "Your communication is serious and purposeful; you prize the word's standing.",
        "aquarius": "You speak independently and differently; you like new, objective ideas.",
        "pisces": "You communicate softly and imagistically; you use metaphor and empathy.",
    },
    4: {
        "aries": "Family is where you take initiative, sometimes hotly; you decide at home.",
        "taurus": "You build a solid, traditional home; you prize material stability.",
        "gemini": "The home is lively and active; you like socializing right at home.",
        "cancer": "Family is your deep root; you protect kin with strong feeling.",
        "leo": "You are the warm center of the family; you like to care and be loved.",
        "virgo": "You care for the home meticulously; you prize real comfort.",
        "libra": "The home is harmonious and aesthetic; you hate conflict indoors.",
        "scorpio": "Family is private and deep for you; bonded yet selective to share.",
        "sagittarius": "You like an open, free home; family links to broadening outlook.",
        "capricorn": "You build family through duty and discipline; you prize tradition.",
        "aquarius": "The home is different and open; you prize each person's freedom.",
        "pisces": "Family is soft and empathic for you; you melt into shared feeling.",
    },
    5: {
        "aries": "You create explosively and lead; affection is warm and direct.",
        "taurus": "You love and create through steady bond; you like beauty and touch.",
        "gemini": "You play varied and curious; affection is light, social, learning.",
        "cancer": "You love deeply and protectively; creativity ties to feeling and nurture.",
        "leo": "You create warmly and like praise; affection is bright and loyal.",
        "virgo": "You create precisely and practically; you love through service and detail.",
        "libra": "You create harmoniously and romantically; affection is light, balanced.",
        "scorpio": "You create and love at high intensity; affection is possessive and transforming.",
        "sagittarius": "You create freely and adventurously; affection is open, expanding together.",
        "capricorn": "You create with discipline and endurance; affection is mature, responsible.",
        "aquarius": "You create differently and independently; affection is friendly, unbound.",
        "pisces": "You create dreamily and empathic; affection dissolves, deeply feeling.",
    },
    6: {
        "aries": "You work fast and take initiative; you prefer action over process.",
        "taurus": "You work steadily and patiently; you prize stability and real output.",
        "gemini": "You juggle tasks and stay flexible; you like communicative, changing work.",
        "cancer": "You work protectively and caringly; health ties to emotion.",
        "leo": "You work confidently and like to lead; you want recognition.",
        "virgo": "You work precisely and correctly; health needs daily discipline.",
        "libra": "You work harmoniously and cooperatively; you like a balanced setting.",
        "scorpio": "You work focused and deep; health is sensitive to inner tension.",
        "sagittarius": "You work openly and meaningfully; you hate rigid routine.",
        "capricorn": "You work with discipline and duty; health builds through steady habit.",
        "aquarius": "You work independently and differently; you like renewal and autonomy.",
        "pisces": "You work empathic and flexibly; health is sensitive to the mental state.",
    },
    7: {
        "aries": "You choose a partner actively and plainly; the bond needs warmth.",
        "taurus": "You need a steady, trustworthy partner; the bond is deeply material.",
        "gemini": "You like a smart, varied partner; the bond needs talk and novelty.",
        "cancer": "You need a protective, empathic partner; the bond ties to safety.",
        "leo": "You like a partner who admires you; the bond is warm and loyal.",
        "virgo": "You need a careful, practical partner; the bond is mutual service.",
        "libra": "You seek a harmonious, aesthetic partner; the bond needs balance.",
        "scorpio": "You need a deep, absolute partner; the bond is possessive and transforming.",
        "sagittarius": "You like an open partner to explore with; the bond needs freedom.",
        "capricorn": "You need a responsible, solid partner; the bond is long and steady.",
        "aquarius": "You like an independent, friendly partner; the bond is unconstrained.",
        "pisces": "You need a soft, empathic partner; the bond dissolves and empathizes.",
    },
    8: {
        "aries": "You approach intimacy directly and explosively; active and passionate, quick to ignite and cool.",
        "taurus": "You bond deeply through body and matter; slow but lasting, loyal yet clinging.",
        "gemini": "You vary how you show closeness; you like exploring and renewing the shared experience.",
        "cancer": "You bond through care and vulnerability; you need safety to open, then very deep.",
        "leo": "You bond warmly and like admiration; you treat closeness as shining together.",
        "virgo": "You are shy, attentive to the other's detail; you show through service, open only with trust.",
        "libra": "You bond harmoniously and aesthetically; closeness needs balance and beauty.",
        "scorpio": "You bond with extreme depth, possession and transformation; demands total trust, loyal to the end.",
        "sagittarius": "You are open and adventurous in bonding; you like expanding together, hate constraint.",
        "capricorn": "You are reserved and restrained; you build bonding long-term through commitment.",
        "aquarius": "You bond differently and independently; you treat closeness as free connection, not possession.",
        "pisces": "You dissolve into bonding, deeply empathic; you need someone grounded to anchor you.",
    },
    9: {
        "aries": "You learn and explore actively; you like leading your own viewpoint.",
        "taurus": "You absorb slowly but surely; you prize practical, traditional knowledge.",
        "gemini": "You crave varied topics and idea exchange; you prefer dialogue to deep study.",
        "cancer": "You learn through feeling and memory; philosophy ties to roots.",
        "leo": "You share views confidently; you learn to shine and lead.",
        "virgo": "You learn precisely and analytically; you prize useful knowledge.",
        "libra": "You seek balance in viewpoints; you like philosophical discussion.",
        "scorpio": "You dig to essence; philosophy is transforming and psychological.",
        "sagittarius": "You hunger to broaden horizons; learning and travel are how you live.",
        "capricorn": "You learn with discipline and system; you prize constructive knowledge.",
        "aquarius": "You learn independently and differently; you like progressive, objective ideas.",
        "pisces": "You learn through intuition and empathy; philosophy is empathic.",
    },
    10: {
        "aries": "You advance actively and lead; you like decisive work.",
        "taurus": "You build a steady career; you prize material standing and stability.",
        "gemini": "You wear many roles and like workplace talk; you shift flexibly.",
        "cancer": "You tie career to a need to protect; you need a safe setting.",
        "leo": "You shine at work and like to lead; you need recognition.",
        "virgo": "You work precisely and correctly; you prize output and service.",
        "libra": "You succeed through cooperation and aesthetics; you like harmony.",
        "scorpio": "You are intense and deep at work; you like power and influence.",
        "sagittarius": "You like meaningful, expanding work; you hate administrative rigidity.",
        "capricorn": "You build career through discipline; you prize standing and steady rise.",
        "aquarius": "You work independently and inventively; you like impacting community.",
        "pisces": "You work empathetically and creatively; you like meaning over fame.",
    },
    11: {
        "aries": "You befriend actively and like leading groups; friends are energetic.",
        "taurus": "You keep long, loyal friends; you prize practical bond.",
        "gemini": "You connect widely and across groups; you like idea exchange.",
        "cancer": "You treat friends like family; the bond ties to care.",
        "leo": "You like being the group's center; friends are warm and loyal.",
        "virgo": "You befriend through help; you prize practical, careful friends.",
        "libra": "You befriend harmoniously; you like balanced groups.",
        "scorpio": "You have few but deep friends; the bond is absolute trust.",
        "sagittarius": "You like open friends to explore with; groups are expanding.",
        "capricorn": "You befriend selectively and steadily; you prize standing in groups.",
        "aquarius": "You connect widely and differently; friends tie to shared ideals.",
        "pisces": "You empathize with friends; the bond is soft and feeling.",
    },
    12: {
        "aries": "You have an active inner drive; sometimes you act from unconscious impulse.",
        "taurus": "You are quiet and need safety in the spiritual; slow but deep.",
        "gemini": "Your unconscious thinks flexibly and multi-sided; you dream and link ideas.",
        "cancer": "You are deeply sensitive in the unconscious; old feeling easily surfaces.",
        "leo": "You carry a strong unconscious ego; you need affirmation even in private.",
        "virgo": "You analyze the inner life precisely; you may worry through detail.",
        "libra": "You seek balance in the spiritual; you swing between poles.",
        "scorpio": "You hold a deep, strong unconscious layer; you may chew on hidden feeling.",
        "sagittarius": "You seek broadly meaningful spirituality; you like free belief.",
        "capricorn": "You discipline even the inner life; you open to the unconscious slowly.",
        "aquarius": "You approach the spiritual objectively and differently; you like timeless view.",
        "pisces": "You fully dissolve into the unconscious; intuition and dream are intense.",
    },
}

# ── OCCUPANT layer: short trait word per planet (used in modifier sentence) ─
# These describe the planet's FLAVOR when it sits in a house (VI / EN).
PLANET_TONE_VI = {
    "sun": "sáng tạo và trung tâm", "moon": "cảm xúc và thay đổi",
    "mercury": "giao tiếp và linh hoạt", "venus": "hài hòa và thu hút",
    "mars": "xung động và hành động", "jupiter": "mở rộng và lạc quan",
    "saturn": "kỷ luật và giới hạn", "uranus": "đột phá và khác biệt",
    "neptune": "mơ mộng và hòa tan", "pluto": "sâu và biến đổi",
    "chiron": "chữa lành và tổn thương", "ceres": "nuôi dưỡng và gắn kết",
    "pallas": "chiến lược và trí tuệ", "juno": "cam kết và trung thành",
    "vesta": "tập trung và tận tâm", "lilith": "nổi loạn và bản năng",
}
PLANET_TONE_EN = {
    "sun": "creative and central", "moon": "emotional and changeable",
    "mercury": "communicative and flexible", "venus": "harmonious and attractive",
    "mars": "impulsive and active", "jupiter": "expansive and optimistic",
    "saturn": "disciplined and limiting", "uranus": "breakthrough and different",
    "neptune": "dreamy and dissolving", "pluto": "deep and transforming",
    "chiron": "healing and wounded", "ceres": "nurturing and attached",
    "pallas": "strategic and intelligent", "juno": "committed and loyal",
    "vesta": "focused and devoted", "lilith": "rebellious and instinctive",
}
